(async()=>{
  const ID='shinobi-suno-bridge',old=document.getElementById(ID);if(old){old.hidden=!old.hidden;return;}
  const C=globalThis.SunoBridgeCore,D=globalThis.SunoBridgeDom;if(!C||!D)return;
  const host=document.createElement('div');host.id=ID;host.style.cssText='position:fixed;top:64px;right:16px;z-index:2147483647';
  const shadow=host.attachShadow({mode:'open'});
  shadow.innerHTML=`<style>:host{all:initial}*{box-sizing:border-box}.p{width:390px;max-height:86vh;overflow:auto;background:#131419;color:#f4f2f6;border:1px solid #ad8b52;border-radius:14px;padding:16px;font:13px/1.45 system-ui;box-shadow:0 15px 60px #000c}.h{display:flex;justify-content:space-between}.brand{font-weight:800;color:#e5c37e;font-size:17px}.muted{color:#aaa;font-size:11px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.full{grid-column:1/-1}button,input,textarea{font:inherit;border-radius:7px;border:1px solid #4b4651;background:#23242c;color:#eee;padding:8px}button{cursor:pointer}button.main{background:#d9b773;color:#161318;font-weight:800}textarea,input{width:100%}textarea{height:120px;resize:vertical}.card{background:#1d1e25;border-radius:8px;padding:9px;margin:8px 0}pre{white-space:pre-wrap;word-break:break-word;margin:0}.row{display:flex;gap:6px}.row>*{flex:1}label{display:block;margin:7px 0}hr{border:0;border-top:1px solid #34343b}</style><div class="p"><div class="h"><div><div class="brand">SHINOBIWAN</div><div class="muted">Suno Bridge · v0.2.2 dev</div></div><button id="close">×</button></div><label>Track Manifest / pack JSON<textarea id="pack" placeholder="Colle directement ici le TRACK MANIFEST généré par ChatGPT…"></textarea></label><div class="muted">Pas besoin d'avoir un fichier pack. Ton bloc TITLE / STYLE PROMPT / LYRICS est déjà importable tel quel.</div><div class="grid" style="margin-top:7px"><input id="file" class="full" type="file" accept=".json,.txt,text/plain,application/json"><button id="parse" class="main">Lire le manifeste</button><button id="example">Charger exemple</button><button id="scan" class="full">Scanner Suno</button></div><label><input id="strip" type="checkbox" style="width:auto"> Retirer les timestamps LRC</label><div class="card"><pre id="summary">Aucun manifeste chargé.</pre></div><div class="card"><pre id="ready">Suno non scanné.</pre></div><div class="grid"><button id="fill" class="main">Remplir titre + style + paroles</button><button id="source">Ouvrir source ↗</button></div><div class="muted">Aucun clic sur Créer / Generate. Tu gardes le dernier clic.</div><hr><details><summary>Réglage / secours</summary><div class="muted">La v0.2 détecte les champs automatiquement. Si nécessaire, désigne-les manuellement.</div><div class="row"><button data-map="title">Titre</button><button data-map="style">Style</button><button data-map="lyrics">Paroles</button></div><button id="clearMap">Effacer les repères</button></details><div class="card"><pre id="status">Colle un Track Manifest ou charge l'exemple de test.</pre></div></div>`;
  document.documentElement.append(host);const $=id=>shadow.getElementById(id),delay=ms=>new Promise(r=>setTimeout(r,ms));
  let {shinobiV02Map:manualMap={}}=await chrome.storage.local.get('shinobiV02Map');let mapping=null,pack=null,lastScan=null;
  const status=t=>$('status').textContent=t;
  const SAMPLE=`TITLE: BRIDGE TEST\nVERSION: V01\nWORKFLOW: Create\nSTYLE PROMPT: Heavy modern electro hip-hop test groove, punchy drums, thick bass, clear male vocal, restrained production.\n\nLYRICS:\n[Intro]\nBridge online.\n\n[Verse 1]\nOne pack in, three fields ready.\n\n[Chorus]\nSHINOBIWAN BRIDGE\nREADY WHEN I AM\n(test back)`;
  function scan(){
    const fields={title:D.autoField('title',manualMap),style:D.autoField('style',manualMap),lyrics:D.autoField('lyrics',manualMap)};
    const expected={workspace:pack?.workspace||'',voice:pack?.voice||'',workflow:pack?.workflow||'',source:pack?.source_url||''};
    const checks={title:!!fields.title,style:!!fields.style,lyrics:!!fields.lyrics,workspace:expected.workspace?D.exactVisibleText(expected.workspace,host):null,voice:expected.voice?D.exactVisibleText(expected.voice,host):null,workflow:expected.workflow?D.workflowOk(expected.workflow,host):null,source:expected.source?location.href.startsWith(expected.source):null};
    lastScan={fields,checks};
    const mark=v=>v===null?'➖':v?'✅':'⚠️';
    const suffix=(value,kind)=>value?' · '+value:` · ${kind==='source'?'non demandée':'non demandé'}`;
    const rows=[['Titre',checks.title,''],['Style',checks.style,''],['Paroles',checks.lyrics,''],['Workspace',checks.workspace,suffix(expected.workspace,'workspace')],['Voice',checks.voice,suffix(expected.voice,'voice')],['Workflow',checks.workflow,suffix(expected.workflow,'workflow')],['Source',checks.source,suffix(expected.source,'source')]];
    $('ready').textContent=rows.map(([n,v,s])=>`${mark(v)} ${n}${s}`).join('\n');return lastScan;
  }
  function renderPack(){if(!pack)return;const lyrics=$('strip').checked?C.stripTimes(pack.lyrics):pack.lyrics;$('summary').textContent=`Titre : ${C.title(pack)}\nWorkflow : ${pack.workflow||'—'}\nWorkspace : ${pack.workspace||'—'}\nVoice : ${pack.voice||'—'}\nStyle : ${pack.style.length} caractères\nParoles : ${lyrics.length} caractères`;}
  $('close').onclick=()=>host.hidden=true;
  $('parse').onclick=()=>{try{pack=C.parse($('pack').value);renderPack();scan();status('Manifeste chargé. Vérifie les lignes ⚠️ avant de remplir.');}catch(e){pack=null;$('summary').textContent='Manifeste invalide.';status(e.message);}};
  $('example').onclick=()=>{$('pack').value=SAMPLE;$('parse').click();status('Exemple de test chargé. Tu peux maintenant remplir Suno sans aucun fichier externe.');};
  $('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(f.size>1024*1024)return status('Fichier > 1 Mo refusé.');$('pack').value=await f.text();$('parse').click();};
  $('strip').onchange=renderPack;$('scan').onclick=()=>{scan();status('Scan actualisé.');};
  $('source').onclick=()=>{if(!pack?.source_url)return status('Aucune source dans ce manifeste.');window.open(pack.source_url,'_blank','noopener,noreferrer');};
  $('fill').onclick=async()=>{try{if(!pack)throw Error('Lis le manifeste d’abord.');const s=scan();for(const k of['title','style','lyrics'])if(!s.fields[k])throw Error(`Champ ${k} introuvable : utilise Réglage / secours.`);const content={title:C.title(pack),style:pack.style,lyrics:$('strip').checked?C.stripTimes(pack.lyrics):pack.lyrics};for(const k of['title','style','lyrics']){D.write(s.fields[k],content[k]);await delay(250);}await delay(500);const normalized=[];for(const k of['title','style','lyrics']){const field=D.autoField(k,manualMap);if(!field)throw Error(`Champ ${k} perdu après remplissage.`);const verdict=C.validateText(k,D.value(field),content[k]);if(!verdict.ok)throw Error(`Validation échouée pour ${k} (${verdict.actualChars}/${verdict.expectedChars} caractères).`);if(verdict.mode==='normalized')normalized.push(k);}scan();status(normalized.length?`✅ Textes validés. Suno a normalisé l'espacement de : ${normalized.join(', ')}. Le contenu est intact.`:'✅ Textes validés exactement. Contrôle Workspace / Voice / workflow puis clique toi-même sur Créer.');}catch(e){status('⚠️ '+e.message);}};
  shadow.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{mapping=b.dataset.map;status(`Clique dans le champ ${mapping} de Suno. Échap pour annuler.`);});
  $('clearMap').onclick=async()=>{manualMap={};await chrome.storage.local.set({shinobiV02Map:{}});status('Repères manuels effacés.');scan();};
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mapping){mapping=null;status('Repérage annulé.');}},true);
  document.addEventListener('click',async e=>{if(!mapping||e.composedPath().includes(host))return;e.preventDefault();e.stopImmediatePropagation();const el=e.target.closest('textarea,input,[contenteditable=true],[contenteditable=plaintext-only]');if(!el||!D.editable(el))return status('Clique dans un champ éditable.');const d=D.descriptor(el);if(!d)return status('Ce champ n’a pas d’identifiant stable.');manualMap[mapping]=d;const done=mapping;mapping=null;await chrome.storage.local.set({shinobiV02Map:manualMap});status(`Repère ${done} enregistré.`);scan();},true);
})();
